# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76df6022b527608ebb43d34757b524639c7209a4ce5bcaec23e7f42720f9b414a352360c6f82cc9719c1de15ce781c7a079c8e55ae39abfa3463590c461ab09c

test:
  secret_key_base: 6a082fedc0313ccec6ba2b4610efd52031e009d144d2e757916c3417c5bcc8230edf31f7f16582dd7be1ffe9d0e2627619d79fc42faa6f9fcf32cf5495a9e24e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
